### ISSUE TITLE
Consider using `std::time::Duration` for timestamps

### ISSUE THREAD

**Issue by walles** [blaind/webp-animation#12]
https://github.com/blaind/webp-animation/blob/abe766438fc0418d88d2664fa510a328b4922277/README.md?plain=1#L25-L26

The type `i32` is used for timestamps in a lot of places.

Do you think you could switch to using Rust's [std::time::Duration](https://doc.rust-lang.org/std/time/struct.Duration.html) for timestamps instead?

This would make the interface look more like Rust and less like C, and it would have saved me some docs reading.

**Comment by blaind** [comment]
I think `Duration` would have different meaning, than the timestamp. 

Since the timestamp in webp library means `timestamp_ms -- (in) timestamp of this frame in milliseconds. Duration of a frame would be calculated as "timestamp of next frame - timestamp of this frame". Hence, timestamps should be in non-decreasing order.`

Durations would make sense, if it depicted the animation-duration of a submitted frame. However, that would require caching one frame and interpolating the duration from the next frame.

**Comment by walles** [comment]
The way I see it is that each frame gets a "timestamp".

However, this is not any generic timestamp, but the duration since the start of the animation at which this particular frame starts. Which could be represented as a `Duration`, no other code changes necessary.

Given your interpretation though, I realize how using `Duration` could be confusing as well...

If you used `timestamp_ms` as the name for the timestamp parameter then that would have helped me.

**Comment by blaind** [comment]
Agreed, the Duration may be confusing. It would also pose new problems with non-ms-aligned durations.

I've created the pull request for renaming the parameter to timestamp_ms, as in webp library.

**Comment by blaind** [comment]
Alleviated by #16

**Comment by blaind** [comment]
This is now released to crates.io in version 0.8
